version: '3.8'

services:
  # ChromaDB Vector Database
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE

  # Streamlit RAG Application
  rag-app:
    build: .
    container_name: rag-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP}
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rag-app.rule=Host(`rag.joel-uzcategui.com`)"
      - "traefik.http.routers.rag-app.service=rag-app"
      - "traefik.http.routers.rag-app.tls=true"
      - "traefik.http.routers.rag-app.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.rag-app.entrypoints=https"
      - "traefik.http.services.rag-app.loadbalancer.server.port=80"
      - "traefik.docker.network=traefik-net"
    depends_on:
      - chromadb
    command: ["streamlit", "run", "src/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  chroma_data:
    driver: local

networks:
  traefik-net:
    external: true