version: '3.8'

services:
  # ChromaDB Vector Database
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE

  # Streamlit RAG Application
  rag-app:
    build: .
    container_name: rag-streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}
      - COLLECTION_NAME=${COLLECTION_NAME}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP}
    depends_on:
      - chromadb
    command: ["streamlit", "run", "src/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  chroma_data:
    driver: local